# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_Home', '0004_articles_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(default='News', max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img_url',
            field=models.CharField(default='http://www.google.com', max_length=300),
        ),
    ]
