# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-01 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_Home', '0005_auto_20161001_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='time',
            field=models.CharField(default='0/0/0', max_length=20),
        ),
    ]
