# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-01 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_Home', '0006_articles_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
