# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-01 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('X_Home', '0007_auto_20161001_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='time',
        ),
    ]
